package org.modelseeed.vault.core;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.zip.DataFormatException;
import java.util.zip.Deflater;
import java.util.zip.DeflaterOutputStream;

import org.bson.types.Binary;

public class Compress {
  
  /**
   * Decompresses a Binary compressed sequence
   * @param compressedSequence Binary compressed sequence
   * @return The original sequence
   * @throws IOException if decompression fails
   */
  public static String decompress(Binary compressedSequence) throws IOException {
      if (compressedSequence == null || compressedSequence.getData().length == 0) {
          return "";
      }
      
      byte[] compressedData = compressedSequence.getData();
      java.util.zip.Inflater inflater = new java.util.zip.Inflater();
      inflater.setInput(compressedData);
      
      ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];
      
      try {
          while (!inflater.finished()) {
              int count = inflater.inflate(buffer);
              outputStream.write(buffer, 0, count);
          }
      } catch (DataFormatException e) {
          throw new IOException("Failed to decompress sequence data", e);
      } finally {
          inflater.end();
          outputStream.close();
      }
      
      return outputStream.toString("UTF-8");
  }
  
  /**
   * Compresses a sequence using zlib compression and returns compressed bytes
   * @param sequence The sequence to compress
   * @return Compressed sequence as byte array
   * @throws IOException if compression fails
   */
  public static byte[] compress(String s) throws IOException {
    if (s == null || s.isEmpty()) {
      return new byte[0];
  }
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    DeflaterOutputStream dos = new DeflaterOutputStream(baos);
    dos.write(s.getBytes(StandardCharsets.UTF_8));
    dos.close(); // Important to close to flush all compressed data
    return baos.toByteArray();
}
  
  /**
   * Compresses a sequence using zlib compression and returns compressed bytes
   * this method was generated by cursor and is not equivalent to python zlib.compress
   * @param sequence The sequence to compress
   * @return Compressed sequence as byte array
   * @throws IOException if compression fails
   */
  public static byte[] compress2(String sequence) throws IOException {
      if (sequence == null || sequence.isEmpty()) {
          return new byte[0];
      }
      
      byte[] input = sequence.getBytes("UTF-8");
      Deflater deflater = new Deflater(Deflater.BEST_COMPRESSION);
      deflater.setInput(input);
      deflater.finish();
      
      ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];
      
      while (!deflater.finished()) {
          int count = deflater.deflate(buffer);
          outputStream.write(buffer, 0, count);
      }
      
      deflater.end();
      outputStream.close();
      
      return outputStream.toByteArray();
  }
  
  /**
   * Creates a Binary object from a base64 encoded compressed sequence
   * @param base64CompressedSequence Base64 encoded compressed sequence
   * @return Binary object for MongoDB storage
   */
  public static Binary createBinaryFromBase64(String base64CompressedSequence) {
      byte[] decodedBytes = Base64.getDecoder().decode(base64CompressedSequence);
      return new Binary(decodedBytes);
  }
}
